#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
    using CES.Core.Cache;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
    using CES.Core.Common;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
    using CES.Core.Models;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
    using Kendo.Mvc.UI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/P_BM_DocImageDetail/_Condition.cshtml")]
    public partial class _Views_P_BM_DocImageDetail__Condition_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_P_BM_DocImageDetail__Condition_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
  
    var curDate = DateTime.Now;
    var company = CurUserInfo.GetCurDBAccount;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"searchform\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-defined-1  col-md-defined-90\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" for=\"CompanyCode\"");

WriteLiteral(">");

            
            #line 11 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
                            Write(CES.Core.Common.CommonSupport.GetLanguageByCode("depbudgetused_g_budgetexecstatisticallist_01"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
    Write(Html.Kendo().DropDownList().Name("CompanyCode")
                        .BindTo(CES.Core.Cache.CacheDataManager.GetAllAccountInfo().Select(p => new { Text = p.AccountName + "(" + p.AccountCode + ")", Value = p.AccountCode }))
                        .DataTextField("Text")
                        .DataValueField("Value").Value("1101")
                        .OptionLabel(CES.Core.Common.CommonSupport.GetLanguageByCode("public_please_swith"))
                        .HtmlAttributes(new { style = "width:345px;float:left;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"an-cls\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-defined-2\"");

WriteLiteral(">\r\n        <label>上传日期</label>\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
    Write(Html.Kendo().DatePicker().Name("DateFm").Format("yyyy-MM-dd").Value(curDate.AddDays(1 - curDate.Day)).HtmlAttributes(new { @style = "width:100%" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"an-cls\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-defined-2\"");

WriteLiteral(">\r\n        <label>至</label>\r\n");

WriteLiteral("        ");

            
            #line 27 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
    Write(Html.Kendo().DatePicker().Name("DateTo").Format("yyyy-MM-dd").Value(curDate).HtmlAttributes(new { @style = "width:100%" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"an-cls\"");

WriteLiteral("></div>\r\n    </div>    \r\n    <div");

WriteLiteral(" class=\"col-md-defined-2\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" name=\"PrgID\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"PrgID\"");

WriteLiteral(" value=\"P_BM_01\"");

WriteLiteral(" />\r\n        <div");

WriteLiteral(" class=\"an-cls\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-defined-2\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" name=\"Compan\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Compan\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1822), Tuple.Create("\"", 1838)
            
            #line 35 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
, Tuple.Create(Tuple.Create("", 1830), Tuple.Create<System.Object, System.Int32>(company
            
            #line default
            #line hidden
, 1830), false)
);

WriteLiteral(" />\r\n        <div");

WriteLiteral(" class=\"an-cls\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-defined-10\"");

WriteLiteral(" style=\"float:right\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"k-button btn2\"");

WriteLiteral(" onclick=\"query();\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
                                                                  Write(CES.Core.Common.CommonSupport.GetLanguageByCode("public_btn_query"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        <button");

WriteLiteral(" class=\"k-button btn1\"");

WriteLiteral(" onclick=\"$(\'#searchform\').data(\'kendoWindow\').close()\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">");

            
            #line 40 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
                                                                                                      Write(CES.Core.Common.CommonSupport.GetLanguageByCode("public_btn_cancel"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        <div");

WriteLiteral(" class=\"an-cls\"");

WriteLiteral(@"></div>
    </div>
</div>
<script>
    $(function () {
        $(""#searchform"").kendoWindow({
            title: ""查询"",
            width: 490,
            modal: true
        });
    });

    function getQueryParams() {
        return { ""PrgID"": ""P_BM_01"", ""Compan"": """);

            
            #line 54 "..\..\Views\P_BM_DocImageDetail\_Condition.cshtml"
                                           Write(company);

            
            #line default
            #line hidden
WriteLiteral(@""" };
    }

    function query(type) {
        var win = $(""#searchform"").data(""kendoWindow"");
        if (type) {
            win.setOptions({
                position: {
                    top: $(document).scrollTop() + 10,
                    left: ""calc(50% - 245px)"",
                }
            });
            win.open();
            return;
        }
        _menu.queryClick()
        win.close();
    }
</script>

");

        }
    }
}
#pragma warning restore 1591
