#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
    using CES.Core.Models;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
    using Kendo.Mvc.UI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/P_BM_DocImageDetail/Index.cshtml")]
    public partial class _Views_P_BM_DocImageDetail_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_P_BM_DocImageDetail_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
  
    Layout = "~/Views/Shared/_ReportLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("FooterContent", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        _base[""PrgID""] = ""P_BM_01"";
        _menu.editClick = function () {
            var grid = $(""#Grid"").data(""kendoGrid"");
            var selectRow = grid.select();
            if (selectRow.length <= 0) {
                var evt = window.event || arguments.callee.caller.arguments[0];
                selectRow = $(evt.srcElement || evt.target).parents(""tr"");
            }

            var dataItem = grid.dataItem(selectRow);            
            if (dataItem[""PrgID""] == ""FA001"")
                top.createTab(""Borrow/See/"" + dataItem[""DataNbr""], """", """);

            
            #line 19 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
                                                                   Write(CES.Core.Common.CommonSupport.GetLanguageByCode("publictipinfo_menu_edit"));

            
            #line default
            #line hidden
WriteLiteral("-");

            
            #line 19 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
                                                                                                                                               Write(CES.Core.Common.CommonSupport.GetLanguageByCode("fa001"));

            
            #line default
            #line hidden
WriteLiteral("\");\r\n            if (dataItem[\"PrgID\"] == \"AC001\")\r\n                top.createTab" +
"(\"BusVerificate/See/\" + dataItem[\"DataNbr\"], \"\", \"");

            
            #line 21 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
                                                                          Write(CES.Core.Common.CommonSupport.GetLanguageByCode("publictipinfo_menu_edit"));

            
            #line default
            #line hidden
WriteLiteral("-");

            
            #line 21 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
                                                                                                                                                      Write(CES.Core.Common.CommonSupport.GetLanguageByCode("ac001"));

            
            #line default
            #line hidden
WriteLiteral("\");\r\n            if (dataItem[\"PrgID\"] == \"AC002\")\r\n                top.createTab" +
"(\"PubPaymentDoc/See/\" + dataItem[\"DataNbr\"], \"\", \"");

            
            #line 23 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
                                                                          Write(CES.Core.Common.CommonSupport.GetLanguageByCode("publictipinfo_menu_edit"));

            
            #line default
            #line hidden
WriteLiteral("-");

            
            #line 23 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
                                                                                                                                                      Write(CES.Core.Common.CommonSupport.GetLanguageByCode("ac002"));

            
            #line default
            #line hidden
WriteLiteral("\");\r\n            if (dataItem[\"PrgID\"] == \"BT003\")\r\n                top.createTab" +
"(\"BtripVerDoc/See/\" + dataItem[\"DataNbr\"], \"\", \"");

            
            #line 25 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
                                                                        Write(CES.Core.Common.CommonSupport.GetLanguageByCode("publictipinfo_menu_edit"));

            
            #line default
            #line hidden
WriteLiteral("-");

            
            #line 25 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
                                                                                                                                                    Write(CES.Core.Common.CommonSupport.GetLanguageByCode("bt003"));

            
            #line default
            #line hidden
WriteLiteral("\");\r\n        }\r\n        function onDataBound(e) {\r\n            $(\".k-i-cancel\").r" +
"emove();\r\n            e.sender.tbody.find(\"tr\").dblclick(function () {\r\n        " +
"        _menu.editClick();\r\n            });\r\n        }\r\n    </script>\r\n");

});

            
            #line 35 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
Write(Html.Partial("_Partial_index_1", new CES.Core.Models.PageInfo
{
    prgID = "P_BM_01",
    prgName = CES.Core.Common.CommonSupport.GetPageTitle("p_bm_01_docimagedetail_ledger")
}));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"ap-order-outline ap-orderlist-outline\"");

WriteLiteral(" id=\"ap-order-outline\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
Write(Html.Partial("_Condition"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"ap-order-scroll ap-orderlist-scroll\"");

WriteLiteral(" id=\"ap-order-scroll\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"am-scrollable-horizontal\"");

WriteLiteral(">\r\n");

            
            #line 45 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\P_BM_DocImageDetail\Index.cshtml"
          Html.RenderAction("GetPartialIndex", new {bCheckBoxColumn = false, bOperationColumn = false });
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
